Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e54eba7c51c234f6
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation]]